// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":false,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"MessageTextSound","status":true,"description":"v1.00 - 为事件的“显示文字”动作添加音效。","parameters":{"Text Sound Interval":"5","Text Sound Name":"Cursor1","Text Sound Volume":"80","Text Sound Pitch":"100","Text Sound Pan":"0"}},
{"name":"LockFPS","status":false,"description":"v1.0 限制游戏最大帧率为60帧","parameters":{}},
{"name":"DisableTouchInput","status":false,"description":"","parameters":{}}
];
